### ISSUE TITLE
Tests fail on FreeBSD 10

### ISSUE THREAD

**Issue by tony** [webpack/watchpack#12]
I'm investigating an issue with two upstream packages, https://github.com/gaearon/react-hot-loader and https://github.com/webpack/webpack-dev-server with this symptom:
- I can save a file once, a file change will be detected.
- I can edit the file again, and the subsequent change won't be detected.

Package cloned from https://github.com/webpack/watchpack/releases/tag/v0.2.8.

``` javascript
{ name: 'watchpack',
  'dist-tags': { latest: '0.2.8' },
  versions: 
   [ '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.1.3',
     '0.2.0',
     '0.2.1',
     '0.2.2',
     '0.2.3',
     '0.2.4',
     '0.2.5',
     '0.2.6',
     '0.2.7',
     '0.2.8' ],
  maintainers: 'sokra <tobias.koppers@googlemail.com>',
  time: 
   { modified: '2015-05-10T12:35:28.755Z',
     created: '2014-10-09T06:48:51.514Z',
     '0.1.0': '2014-10-09T06:48:51.514Z',
     '0.1.1': '2014-11-02T22:53:10.008Z',
     '0.1.2': '2014-11-11T23:07:10.341Z',
     '0.1.3': '2014-11-18T22:53:53.283Z',
     '0.2.0': '2015-01-17T18:12:02.174Z',
     '0.2.1': '2015-01-17T20:50:59.908Z',
     '0.2.2': '2015-01-20T22:45:35.020Z',
     '0.2.3': '2015-01-24T09:50:39.292Z',
     '0.2.4': '2015-04-09T14:36:32.928Z',
     '0.2.5': '2015-04-30T18:50:59.017Z',
     '0.2.6': '2015-05-03T21:05:25.570Z',
     '0.2.7': '2015-05-10T11:33:12.879Z',
     '0.2.8': '2015-05-10T12:35:28.755Z' },
  homepage: 'https://github.com/webpack/watchpack',
  repository: 
   { type: 'git',
     url: 'git+https://github.com/webpack/watchpack.git' },
  author: 'Tobias Koppers @sokra',
  bugs: { url: 'https://github.com/webpack/watchpack/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  description: 'Wrapper library for directory and file watching.',
  version: '0.2.8',
  main: './lib/watchpack.js',
  directories: { test: 'test' },
  scripts: 
   { pretest: 'npm run lint',
     test: 'mocha',
     travis: 'npm run cover -- --report lcovonly',
     lint: 'eslint lib',
     precover: 'npm run lint',
     cover: 'istanbul cover node_modules/mocha/bin/_mocha' },
  devDependencies: 
   { coveralls: '^2.11.2',
     eslint: '^0.20.0',
     istanbul: '^0.3.13',
     mocha: '^2.1.0',
     rimraf: '^2.2.8',
     should: '^6.0.1' },
  dependencies: { async: '^0.9.0', chokidar: '^1.0.0', 'graceful-fs': '^3.0.2' },
  gitHead: '3f5ec9863c36dbee8b5e3d9a2a730c1f3d02b993',
  dist: 
   { shasum: '3234d3648e72a43f25c225fb8ff12877d3f4ac47',
     tarball: 'http://registry.npmjs.org/watchpack/-/watchpack-0.2.8.tgz' } }
```

System:

``` sh
$ uname -apKU
FreeBSD z600 10.2-PRERELEASE FreeBSD 10.2-PRERELEASE #5: Fri Jun 26 10:34:21 CDT 2015     root@z600:/usr/obj/usr/src/sys/MYKERNEL  amd64 amd64 1001519 1001519
```

Output of 

``` sh
> watchpack@0.2.8 pretest /usr/home/tony/work/watchpack
> npm run lint


> watchpack@0.2.8 lint /usr/home/tony/work/watchpack
> eslint lib


> watchpack@0.2.8 test /usr/home/tony/work/watchpack
> mocha



  DirectoryWatcher

    ✓ should detect a file creation (128ms)

    1) should detect a file change
DirectoryWatcher (/usr/home/tony/work/watchpack/test/fixtures) was not closed.

    ✓ should not detect a file change in initial scan (211ms)

    ✓ should detect a file change in initial scan with start date (2013ms)

    ✓ should not detect a file change in initial scan without start date (205ms)

    2) should detect multiple file changes (slow)
DirectoryWatcher (/usr/home/tony/work/watchpack/test/fixtures) was not closed.

    3) should detect multiple file changes (fast)
DirectoryWatcher (/usr/home/tony/work/watchpack/test/fixtures) was not closed.

  Watchpack

    ✓ should watch a single file (1133ms)

    4) should watch multiple files

    5) "after each" hook

  5 passing (41s)
  5 failing

  1) DirectoryWatcher should detect a file change:
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.


  2) DirectoryWatcher should detect multiple file changes (slow):
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.


  3) DirectoryWatcher should detect multiple file changes (fast):
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.


  4) Watchpack should watch multiple files:

      Uncaught expected [
  '/usr/home/tony/work/watchpack/test/fixtures/a',
  '/usr/home/tony/work/watchpack/test/fixtures/b'
] to equal [
  '/usr/home/tony/work/watchpack/test/fixtures/a',
  '/usr/home/tony/work/watchpack/test/fixtures/b',
  '/usr/home/tony/work/watchpack/test/fixtures/a',
  '/usr/home/tony/work/watchpack/test/fixtures/b',
  '/usr/home/tony/work/watchpack/test/fixtures/a'
] (at length, A has 2 and B has 5)
      + expected - actual

       [
         "/usr/home/tony/work/watchpack/test/fixtures/a"
         "/usr/home/tony/work/watchpack/test/fixtures/b"
      +  "/usr/home/tony/work/watchpack/test/fixtures/a"
      +  "/usr/home/tony/work/watchpack/test/fixtures/b"
      +  "/usr/home/tony/work/watchpack/test/fixtures/a"
       ]

  AssertionError: expected [
    'test/fixtures/a',
    'test/fixtures/b'
  ] to equal [
    'test/fixtures/a',
    'test/fixtures/b',
    'test/fixtures/a',
    'test/fixtures/b',
    'test/fixtures/a'
  ] (at length, A has 2 and B has 5)
      at EventEmitter.<anonymous> (test/watchpack.js:48:27)
      at EventEmitter._onTimeout (lib/watchpack.js:121:7)

  5) Watchpack "after each" hook:

      Uncaught expected [ '/usr/home/tony/work/watchpack/test/fixtures {}' ] to equal [] (at length, A has 1 and B has 0)
      + expected - actual

      -[
      -  "/usr/home/tony/work/watchpack/test/fixtures {}"
      -]
      +[]

  AssertionError: expected [ 'test/fixtures {}' ] to equal [] (at length, A has 1 and B has 0)
      at TestHelper.<anonymous> (test/helpers/TestHelper.js:31:59)
      at null._onTimeout (test/helpers/TestHelper.js:59:3)
```

**Comment by tony** [comment]
It seems this could be an OS issue.  FreeBSD's file watching utilities (kqueue) are different than OSX, Linux, etc.

I checked on another OS (Ubuntu 15.04 Vivid) I do not have these symptoms on https://github.com/gaearon/react-hot-loader and https://github.com/webpack/webpack-dev-server and the tests complete fine.

**Comment by tony** [comment]
Greetings. I think we should keep this issue open, it's a real bug - the blocker is upstream.

https://github.com/paulmillr/chokidar/issues/309

This fits in with the test errors above in watchpack and the behavior I experience when using watchpack.

**Comment by SpaceK33z** [comment]
@tony, is this fixed?

**Comment by tony** [comment]
@SpaceK33z It's been a long time since I made the thread. I worked around it by passing enabling polling.

I'm going to close it for now, if someone continues to have the issue in some form they can re-open or cite this.

**Comment by strictd** [comment]
We just had this issue. The core issue is how the watched file is being written to. In our case rsync was replacing the file. Adding --inplace switch to our rsync command solved this problem.
