### ISSUE TITLE
npm test fails on OSX

### ISSUE THREAD

**Issue by gajus** [webpack/watchpack#14]
ProductName:    Mac OS X
ProductVersion: 10.10.4
BuildVersion:   14E17e

```
curiosity:watchpack gajus$ npm test

> watchpack@0.2.8 pretest /Users/gajus/watchpack
> npm run lint


> watchpack@0.2.8 lint /Users/gajus/watchpack
> eslint lib


> watchpack@0.2.8 test /Users/gajus/watchpack
> mocha



  DirectoryWatcher
    ✓ should detect a file creation (131ms)
    ✓ should detect a file change (187ms)
    ✓ should not detect a file change in initial scan (207ms)
    ✓ should detect a file change in initial scan with start date (2006ms)
    ✓ should not detect a file change in initial scan without start date (204ms)
    ✓ should detect multiple file changes (slow) (7014ms)
    ✓ should detect multiple file changes (fast) (2528ms)

  Watchpack
    ✓ should watch a single file (1118ms)
    ✓ should watch multiple files (1552ms)
    ✓ should watch a directory (1252ms)
    1) should watch a file than a directory
    2) "after each" hook

  10 passing (25s)
  2 failing

  1) Watchpack should watch a file than a directory:

      Uncaught expected [
  '/Users/gajus/watchpack/test/fixtures/dir/a',
  '/Users/gajus/watchpack/test/fixtures/dir'
] to equal [ '/Users/gajus/watchpack/test/fixtures/dir' ] (at length, A has 2 and B has 1)
      + expected - actual

       [
      -  "/Users/gajus/watchpack/test/fixtures/dir/a"
         "/Users/gajus/watchpack/test/fixtures/dir"
       ]

  AssertionError: expected [
    'test/fixtures/dir/a',
    'test/fixtures/dir'
  ] to equal [ 'test/fixtures/dir' ] (at length, A has 2 and B has 1)
      at EventEmitter.<anonymous> (test/watchpack.js:116:22)
      at EventEmitter._onTimeout (lib/watchpack.js:121:7)

  2) Watchpack "after each" hook:

      Uncaught expected [
  '/Users/gajus/watchpack/test/fixtures/dir {}',
  '/Users/gajus/watchpack/test/fixtures {}',
  '/Users/gajus/watchpack/test/fixtures/dir/subdir {}'
] to equal [] (at length, A has 3 and B has 0)
      + expected - actual

      -[
      -  "/Users/gajus/watchpack/test/fixtures/dir {}"
      -  "/Users/gajus/watchpack/test/fixtures {}"
      -  "/Users/gajus/watchpack/test/fixtures/dir/subdir {}"
      -]
      +[]

  AssertionError: expected [
    'test/fixtures/dir {}',
    'test/fixtures {}',
    'test/fixtures/dir/subdir {}'
  ] to equal [] (at length, A has 3 and B has 0)
      at TestHelper.<anonymous> (test/helpers/TestHelper.js:31:59)
      at null._onTimeout (test/helpers/TestHelper.js:59:3)



npm ERR! Test failed.  See above for more details.
```

**Comment by yuchonghua** [comment]
I have encountered the same problem with you. This automatic test actually has a random error. In fact, this error is not only on Mac OS X, but it is possible to trigger the error on any test.

see: https://github.com/webpack/watchpack/issues/98

/ping @gajus

**Comment by HadiChen** [comment]
see: https://travis-ci.org/webpack/watchpack/jobs/492541153
![image](https://user-images.githubusercontent.com/17898715/52691125-d23a0e80-2f9a-11e9-87b4-dc31df7f19f1.png)

see:https://travis-ci.org/webpack/watchpack/jobs/492544121
![image](https://user-images.githubusercontent.com/17898715/52691172-f269cd80-2f9a-11e9-9cc2-201f684439c3.png)

see: pr : https://github.com/webpack/watchpack/pull/96 https://github.com/webpack/watchpack/pull/97

Do you see if the results of this automated test are very similar?

/ping @gajus @evilebottnawi @sokra

**Comment by yuchonghua** [comment]
@see: https://travis-ci.org/webpack/watchpack/builds/492552129?utm_source=github_status&utm_medium=notification

---

![image](https://user-images.githubusercontent.com/17898715/52692895-1e3b8200-2fa0-11e9-90f5-b063ee47e55f.png)

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/watchpack/issues/98
