### ISSUE TITLE
[Yarn2/PnP] Recompilation fails: "Error: Can't open file: No file descriptors available"

### ISSUE THREAD

**Issue by nkalinov** [webpack/watchpack#142]
I'm trying to migrate our project to Yarn2 using its new PnP resolution mechanism. In watch mode, using webpack-dev-server, whenever I change a file, something screws up.
The initial compilation works fine.

```
/Users/nkalinov/dev/simonapp/.pnp.js:39844
    throw firstError;
    ^

Error: Can't open file: No file descriptors available
Require stack:
- /Users/nkalinov/dev/simonapp/.yarn/cache/watchpack-npm-1.6.0-2e77885616-1.zip/node_modules/watchpack/lib/watcherManager.js
- /Users/nkalinov/dev/simonapp/.yarn/cache/watchpack-npm-1.6.0-2e77885616-1.zip/node_modules/watchpack/lib/watchpack.js
- /Users/nkalinov/dev/simonapp/.yarn/cache/webpack-npm-4.41.5-ec6f53e9d3-1.zip/node_modules/webpack/lib/node/NodeWatchFileSystem.js
- /Users/nkalinov/dev/simonapp/.yarn/cache/webpack-npm-4.41.5-ec6f53e9d3-1.zip/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js
- /Users/nkalinov/dev/simonapp/.yarn/cache/webpack-npm-4.41.5-ec6f53e9d3-1.zip/node_modules/webpack/lib/webpack.js
- /Users/nkalinov/dev/simonapp/.yarn/$$virtual/webpack-dev-server-virtual-d46dc61805/0/cache/webpack-dev-server-npm-3.10.1-34b49b6a2b-1.zip/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at new ZipFS (/Users/nkalinov/dev/simonapp/.pnp.js:28860:15)
    at ZipOpenFS.getZipSync (/Users/nkalinov/dev/simonapp/.pnp.js:33358:52)
    at ZipOpenFS.makeCallSync (/Users/nkalinov/dev/simonapp/.pnp.js:33257:17)
    at ZipOpenFS.existsSync (/Users/nkalinov/dev/simonapp/.pnp.js:32755:17)
    at VirtualFS.existsSync (/Users/nkalinov/dev/simonapp/.pnp.js:27279:24)
    at /Users/nkalinov/dev/simonapp/.pnp.js:40152:28
    at Array.find (<anonymous>)
    at applyNodeExtensionResolution (/Users/nkalinov/dev/simonapp/.pnp.js:40150:10)
    at resolveUnqualified (/Users/nkalinov/dev/simonapp/.pnp.js:40504:27)
    at resolveRequest (/Users/nkalinov/dev/simonapp/.pnp.js:40536:14)
    at Object.resolveRequest (/Users/nkalinov/dev/simonapp/.pnp.js:40598:26)
    at Function.module_1.Module._resolveFilename (/Users/nkalinov/dev/simonapp/.pnp.js:39827:34)
    at Function.module_1.Module._load (/Users/nkalinov/dev/simonapp/.pnp.js:39712:40)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at WatcherManager.getDirectoryWatcher (/Users/nkalinov/dev/simonapp/.yarn/cache/watchpack-npm-1.6.0-2e77885616-1.zip/node_modules/watchpack/lib/watcherManager.js:14:25) {
  requireStack: [
    '/Users/nkalinov/dev/simonapp/.yarn/cache/watchpack-npm-1.6.0-2e77885616-1.zip/node_modules/watchpack/lib/watcherManager.js',
    '/Users/nkalinov/dev/simonapp/.yarn/cache/watchpack-npm-1.6.0-2e77885616-1.zip/node_modules/watchpack/lib/watchpack.js',
    '/Users/nkalinov/dev/simonapp/.yarn/cache/webpack-npm-4.41.5-ec6f53e9d3-1.zip/node_modules/webpack/lib/node/NodeWatchFileSystem.js',
    '/Users/nkalinov/dev/simonapp/.yarn/cache/webpack-npm-4.41.5-ec6f53e9d3-1.zip/node_modules/webpack/lib/node/NodeEnvironmentPlugin.js',
    '/Users/nkalinov/dev/simonapp/.yarn/cache/webpack-npm-4.41.5-ec6f53e9d3-1.zip/node_modules/webpack/lib/webpack.js',
    '/Users/nkalinov/dev/simonapp/.yarn/$$virtual/webpack-dev-server-virtual-d46dc61805/0/cache/webpack-dev-server-npm-3.10.1-34b49b6a2b-1.zip/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
```

OS: **OSX**
Node version: tried both **v12.14.1** and latest **v10**
Yarn version: **2.0.0-rc.28**
Related Yarn issue: https://github.com/yarnpkg/berry/issues/849

**Comment by arcanis** [comment]
We're looking into that (although I'm not sure how to repro as our own app is fine 🤔)

**Comment by nkalinov** [comment]
Thanks guys, I'll try to repro by extracting our setup (webpack, babel etc..) in a separate public repo in the next few days if that will help.

**Comment by nkalinov** [comment]
Hey, I wasn't able to extract a repro project neither to identify a stable pattern when it happens.
Not sure if you checked the berry issue but there are other people experiencing it too and they provided some info (hopefully helpful): https://github.com/yarnpkg/berry/issues/849

**Comment by rtsao** [comment]
I think I've identified a possible workaround: https://github.com/yarnpkg/berry/issues/849#issuecomment-641550874

**Comment by evilebottnawi** [comment]
@rtsao Can you send a fix?

**Comment by rtsao** [comment]
I could wrap that code in a `if (process.versions.pnp) {` check. Obviously seems unfortunate to have hardcoded workaround for Yarn v2 though.

@arcanis am I correct in that file watchers don't make any sense for virtual paths? They don't actually exist on disk and they are immutable, no?

**Comment by merceyz** [comment]
> @arcanis am I correct in that file watchers don't make any sense for virtual paths? They don't actually exist on disk and they are immutable, no?

Not exactly, they can point to local workspaces which are mutable

**Comment by irudoy** [comment]
Have exactly the same issue after upgrading `webpack` from `4.43.0` to `4.44.1`.
Also, after WDS is failing, seems like `.pnp.js` or `pnpify typescript sdk` is broken (ide can't resolve any modules from typescript files).

Doesn't investigated too much, but seems like there's an issue with `chokidar`, which was updated in `watchpack` `1.7.2`.

Hotfixed by forcing `watchpack` resolution to `1.6.1` in my project.

**Comment by evilebottnawi** [comment]
@irudoy Can you provide reproducible test repo>

**Comment by irudoy** [comment]
@evilebottnawi I'll try later, but not sure if it will be succeeded

**Comment by evilebottnawi** [comment]
@rtsao maybe screenshot or other examples?

**Comment by irudoy** [comment]
Unfortunately, I had no luck trying to reduce my project preserving reproducibility.
Every time when I tried to change entries/modules, the issue doesn't reproduce anymore.
Also tried to generate a lot of dummy modules (>100000) simulating a big project, but with no luck.

**Comment by evilebottnawi** [comment]
@irudoy weird, maybe fixed?

**Comment by irudoy** [comment]
@evilebottnawi I can still reproduce it on our project in the current state, but not on the reduced one

**Comment by merceyz** [comment]
You'll most likely need peer dependencies to make it happen, seems to be the virtual files that cause the issue

**Comment by evilebottnawi** [comment]
@irudoy yep, can you try to update deps and regenerate lock file?

**Comment by irudoy** [comment]
update deps, rm yarn.lock, install -> still having an issue, unfortunately

**Comment by evilebottnawi** [comment]
@irudoy Can you record video/screenshots?

**Comment by irudoy** [comment]
@evilebottnawi https://www.dropbox.com/s/ebxy7k184rn5mvl/watchpack-142.mov?dl=1

**Comment by evilebottnawi** [comment]
@irudoy weird, ambye you can provide configuration, especial the `resolve` section https://webpack.js.org/configuration/resolve/

**Comment by irudoy** [comment]
@evilebottnawi 

```
import PnpWebpackPlugin from 'pnp-webpack-plugin';

resolve: {
  extensions: ['.js', '.ts', '.tsx'],
  plugins: [PnpWebpackPlugin],
},
```

**Comment by irudoy** [comment]
<details>
  <summary>Webpack config</summary>
  
  ```javascript
  Object {
    "devtool": "cheap-module-eval-source-map",
    "entry": "<<ENTRY>>",
    "externals": Object {
      "$": "jQuery",
      "jQuery": "jQuery",
      "jquery": "jQuery",
    },
    "mode": "development",
    "module": Object {
      "rules": Array [
        Object {
          "oneOf": Array [
            Object {
              "exclude": /node_modules/,
              "test": /\\.((js|ts)x?|mjs)$/,
              "use": Object {
                "loader": /.yarn/$$virtual/babel-loader-virtual-4a6f2ff303/0/cache/babel-loader-npm-8.1.0-e8c38740ba-3.zip/node_modules/babel-loader/lib/index.js,
                "options": Object {
                  "cacheCompression": false,
                  "cacheDirectory": false,
                },
              },
            },
            Object {
              "test": /\\.css$/,
              "use": Array [
                Object {
                  "loader": /.yarn/cache/style-loader-npm-0.23.1-107a4d9281-3.zip/node_modules/style-loader/index.js,
                  "options": Object {
                    "sourceMap": true,
                  },
                },
                Object {
                  "loader": /.yarn/$$virtual/css-loader-virtual-5c70e9335b/0/cache/css-loader-npm-4.2.1-c1cda84612-3.zip/node_modules/css-loader/dist/cjs.js,
                  "options": Object {
                    "url": true,
                  },
                },
                Object {
                  "loader": /.yarn/cache/postcss-loader-npm-3.0.0-f4ab99b685-3.zip/node_modules/postcss-loader/src/index.js,
                  "options": Object {
                    "ident": "postcss",
                    "plugins": Array [
                      [Function],
                      [Function],
                    ],
                    "sourceMap": true,
                  },
                },
              ],
            },
            Object {
              "test": /\\.styl$/,
              "use": Array [
                Object {
                  "loader": /.yarn/cache/style-loader-npm-0.23.1-107a4d9281-3.zip/node_modules/style-loader/index.js,
                  "options": Object {
                    "sourceMap": true,
                  },
                },
                Object {
                  "loader": /.yarn/cache/postcss-loader-npm-3.0.0-f4ab99b685-3.zip/node_modules/postcss-loader/src/index.js,
                  "options": Object {
                    "ident": "postcss",
                    "plugins": Array [
                      [Function],
                      [Function],
                    ],
                    "sourceMap": true,
                  },
                },
                Object {
                  "loader": /.yarn/$$virtual/stylus-loader-virtual-08d45a078a/0/cache/stylus-loader-npm-3.0.2-e1aa9f1962-3.zip/node_modules/stylus-loader/index.js,
                  "options": Object {
                    "import": Array [
                      <<>>
                    ],
                    "sourceMap": Object {
                      "inline": true,
                    },
                  },
                },
              ],
            },
            Object {
              "resourceQuery": /component/,
              "test": /\\.svg$/,
              "use": Array [
                Object {
                  "loader": /.yarn/$$virtual/babel-loader-virtual-4a6f2ff303/0/cache/babel-loader-npm-8.1.0-e8c38740ba-3.zip/node_modules/babel-loader/lib/index.js,
                  "options": Object {
                    "cacheCompression": false,
                    "cacheDirectory": false,
                  },
                },
                Object {
                  "loader": /.yarn/cache/@svgr-webpack-npm-4.3.3-e4a44d50b7-3.zip/node_modules/@svgr/webpack/lib/index.js,
                  "options": Object {
                    "babel": false,
                  },
                },
              ],
            },
            Object {
              "resourceQuery": /datauri/,
              "test": /\\.svg$/,
              "use": Array [
                Object {
                  "loader": /.yarn/$$virtual/svg-url-loader-virtual-e9caba6b8e/0/cache/svg-url-loader-npm-6.0.0-c65934e254-3.zip/node_modules/svg-url-loader/index.js,
                  "options": Object {
                    "limit": 9007199254740991,
                    "name": "media/[name].[contenthash].[ext]",
                  },
                },
                Object {
                  "loader": /.yarn/$$virtual/svgo-loader-virtual-f9e46f99db/0/cache/svgo-loader-npm-2.2.1-365096fbc4-3.zip/node_modules/svgo-loader/index.js,
                },
              ],
            },
            Object {
              "test": /\\.svg$/,
              "use": Array [
                Object {
                  "loader": /.yarn/$$virtual/file-loader-virtual-3c537dac52/0/cache/file-loader-npm-4.1.0-9a72a3c95d-3.zip/node_modules/file-loader/dist/cjs.js,
                  "options": Object {
                    "name": "media/[name].[contenthash].[ext]",
                  },
                },
                Object {
                  "loader": /.yarn/$$virtual/svgo-loader-virtual-f9e46f99db/0/cache/svgo-loader-npm-2.2.1-365096fbc4-3.zip/node_modules/svgo-loader/index.js,
                },
              ],
            },
            Object {
              "resourceQuery": /datauri/,
              "test": /\\.(png|jpe?g|gif|eot|ttf|woff|woff2)$/,
              "use": Array [
                Object {
                  "loader": /.yarn/$$virtual/url-loader-virtual-cfc41b028e/0/cache/url-loader-npm-2.1.0-0c6c53db3d-3.zip/node_modules/url-loader/dist/cjs.js,
                  "options": Object {
                    "limit": 9007199254740991,
                    "name": "media/[name].[contenthash].[ext]",
                  },
                },
                Object {
                  "loader": /.yarn/cache/image-webpack-loader-npm-5.0.0-bbfab6a8ce-3.zip/node_modules/image-webpack-loader/index.js,
                  "options": Object {
                    "disable": true,
                    "mozjpeg": Object {
                      "quality": 85,
                    },
                  },
                },
              ],
            },
            Object {
              "test": /\\.(png|jpe?g|gif|eot|ttf|woff|woff2)$/,
              "use": Array [
                Object {
                  "loader": /.yarn/$$virtual/file-loader-virtual-3c537dac52/0/cache/file-loader-npm-4.1.0-9a72a3c95d-3.zip/node_modules/file-loader/dist/cjs.js,
                  "options": Object {
                    "name": "media/[name].[contenthash].[ext]",
                  },
                },
                Object {
                  "loader": /.yarn/cache/image-webpack-loader-npm-5.0.0-bbfab6a8ce-3.zip/node_modules/image-webpack-loader/index.js,
                  "options": Object {
                    "disable": true,
                    "mozjpeg": Object {
                      "quality": 85,
                    },
                  },
                },
              ],
            },
            Object {
              "exclude": Array [
                /\\.((js|ts)x?|mjs)$/,
                /\\.html$/,
                /\\.json$/,
              ],
              "loader": /.yarn/$$virtual/file-loader-virtual-3c537dac52/0/cache/file-loader-npm-4.1.0-9a72a3c95d-3.zip/node_modules/file-loader/dist/cjs.js,
              "options": Object {
                "name": "media/[name].[contenthash].[ext]",
              },
            },
          ],
        },
      ],
      "strictExportPresence": true,
    },
    "node": Object {
      "child_process": "empty",
      "dgram": "empty",
      "fs": "empty",
      "net": "empty",
      "path": "empty",
      "tls": "empty",
    },
    "output": Object {
      "chunkFilename": "[name].chunk.js",
      "crossOriginLoading": "anonymous",
      "filename": "[name].js",
      "jsonpFunction": "dromWebpackJsonp",
      "path": /build,
      "publicPath": "<<PUBLIC_PATH>>",
    },
    "performance": Object {
      "assetFilter": [Function],
    },
    "plugins": Array [
      DefinePlugin {
        "definitions": Object {
          "__DEV__": true,
          "__RELEASE__": false,
        },
      },
      MiniCssExtractPlugin {
        "options": Object {
          "chunkFilename": "[name].[contenthash].chunk.css",
          "filename": "[name].[contenthash].css",
          "ignoreOrder": false,
          "moduleFilename": [Function],
        },
      },
      IgnorePlugin {
        "checkIgnore": [Function],
        "options": Object {
          "contextRegExp": /moment$/,
          "resourceRegExp": /^\\.\\/locale$/,
        },
      },
      Object {},
      NamedModulesPlugin {
        "options": Object {},
      },
      HotModuleReplacementPlugin {
        "fullBuildTimeout": 200,
        "multiStep": undefined,
        "options": Object {},
        "requestTimeout": 10000,
      },
      EncodingPlugin {
        "options": Object {
          "encoding": "windows-1251",
          "test": /(\\.js|\\.css)($|\\?)/i,
        },
      },
      LoadablePlugin {
        "compiler": null,
        "handleEmit": [Function],
        "opts": Object {
          "filename": "loadable-stats.json",
          "outputAsset": true,
          "path": undefined,
          "writeToDisk": undefined,
        },
        "writeAssetsFile": [Function],
      },
    ],
    "resolve": Object {
      "extensions": Array [
        ".js",
        ".ts",
        ".tsx",
      ],
      "plugins": Array [
        Object {
          "apply": [Function],
          "bind": [Function],
          "forkTsCheckerOptions": [Function],
          "makePlugin": [Function],
          "moduleLoader": [Function],
          "topLevelLoader": Object {
            "apply": [Function],
          },
          "tsLoaderOptions": [Function],
        },
      ],
    },
    "resolveLoader": Object {
      "plugins": Array [
        Object {
          "apply": [Function],
        },
      ],
    },
  }
  ```
  
</details>

**Comment by evilebottnawi** [comment]
@irudoy Do you use `webpack@4` or `webpack@5`? `PnpWebpackPlugin` has bugs in some rare cases, you can find what our source code for pnp is not the same as in `PnpWebpackPlugin`

**Comment by irudoy** [comment]
@evilebottnawi webpack 4 for now

**Comment by evilebottnawi** [comment]
@irudoy Just interesting can you try `webpack@5`? I'm afraid we won't fix it on our side right

**Comment by irudoy** [comment]
@evilebottnawi got this with `webpack@5`

```
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: EBUSY: archive closed, lstat '/node_modules/terser-webpack-plugin'
    [webpack.cache.PackFileCacheStrategy] Error: EBUSY: archive closed, lstat '/node_modules/terser-webpack-plugin'
        at makeError (/Users/rudoy/src/drom/.pnp.js:41561:24)
        at Object.EBUSY (/Users/rudoy/src/drom/.pnp.js:41567:10)
        at ZipFS.resolveFilename (/Users/rudoy/src/drom/.pnp.js:40739:35)
        at ZipFS.realpathSync (/Users/rudoy/src/drom/.pnp.js:40580:28)
        at ZipFS.realpathPromise (/Users/rudoy/src/drom/.pnp.js:40576:17)
        at /Users/rudoy/src/drom/.pnp.js:42387:150
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at /Users/rudoy/src/drom/.pnp.js:42904:73
        at ZipOpenFS.getZipPromise (/Users/rudoy/src/drom/.pnp.js:43005:14)
```

not sure that it's related to this issue

**Comment by irudoy** [comment]
It happens with persistent caching enabled, of course. When caching is disabled, the first-time build succeeds, but file watching is not working. WDS doesn't triggers rebuild after some file has been updated.

**Comment by merceyz** [comment]
Those methods don't really use file handles but it could be https://github.com/yarnpkg/berry/pull/1577, could you try updating to yarn from sources? `yarn set version from sources --no-minify`

**Comment by merceyz** [comment]
I'm able to reproduce, i'll make a fix to Yarn and let you know

**Comment by irudoy** [comment]
Nice 😄 Also, seems like this issue (about `No file descriptors available`) is not reproducing at the latest yarn version (from master)

**Comment by merceyz** [comment]
Should be fixed in https://github.com/yarnpkg/berry/pull/1709, could you try with `yarn set version from sources --branch 1709`?

**Comment by evilebottnawi** [comment]
So problem on yarn side, right? It's good that we found them

**Comment by irudoy** [comment]
@merceyz not throwing anymore, thanks!

**Comment by evilebottnawi** [comment]
@irudoy Can we close? Solutions - update yarn to latest stable version, I hope `#1709` will be merged in near future

**Comment by irudoy** [comment]
@evilebottnawi issue doesn't appear using the latest yarn build. So I think it can be closed, thanks!

**Comment by merceyz** [comment]
@evilebottnawi I only fixed https://github.com/webpack/watchpack/issues/142#issuecomment-675307821, which is unrelated to the original issue.

**Comment by evilebottnawi** [comment]
@merceyz this does not happen on the latest version https://github.com/webpack/watchpack/issues/142#issuecomment-675353818, so let's close, if somebody faced with the issue again - please update yarn to latest version, if it is not help - feel free to open new issue (preferably with a reproducible version)
