### ISSUE TITLE
Crash error after upgrade required package chokidar to up 1.1.0 

### ISSUE THREAD

**Issue by centum** [webpack/watchpack#18]
I use webpack in watch mode. After upgrade required package **chokidar** to version up 1.1.0 raise error:
```bash
/home/vadim/project/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/readdirp/readdirp.js:52
    var api          =  require('./stream-api')();
                                               ^
TypeError: object is not a function
    at readdir (/home/vadim/project/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/readdirp/readdirp.js:52:48)
    at EventEmitter.<anonymous> (/home/vadim/project/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/nodefs-handler.js:353:5)
    at EventEmitter.NodeFsHandler._handleDir (/home/vadim/project/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/nodefs-handler.js:402:18)
    at EventEmitter.<anonymous> (/home/vadim/project/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/nodefs-handler.js:450:19)
    at EventEmitter.<anonymous> (/home/vadim/project/node_modules/webpack/node_modules/watchpack/node_modules/chokidar/lib/nodefs-handler.js:455:16)
    at Object.oncomplete (fs.js:108:15)
npm ERR! weird error 8
npm ERR! not ok code 0
```
With chokidar@1.0.5 with error don't raise.

**Comment by sokra** [comment]
I assume this is no longer an issue.
