### ISSUE TITLE
Migration to v2 gives directory path errors

### ISSUE THREAD

**Issue by gita-vahdatinia** [webpack/watchpack#185]
I upgraded to webpackv5 and the watchpack v2 is now giving incorrect filepaths. 

My context is set to `/Users/gita/code/experimental`
I put some output statements in `DirectoryWatcher.js` to see what is being set as the directoryPath and filePath 
The inital print statements show the following are first set for DirectoryWatcher and Watcher in the constructor
```2020-12-10-15:58:07 1|worker-webpack  | directoryPath of DirectoryWatcher /Users/gita/code/experimental
2020-12-10-15:58:07 1|worker-webpack  | directoryPath of DirectoryWatcher /Users/gita/code
2020-12-10-15:58:07 1|worker-webpack  | directoryPath of DirectoryWatcher /Users/gita
2020-12-10-15:58:07 1|worker-webpack  | directoryPath of DirectoryWatcher /Users
2020-12-10-15:58:07 1|worker-webpack  | filePath of Watcher /Users/gita
2020-12-10-15:58:07 1|worker-webpack  | filePath of Watcher /Users/gita/code
2020-12-10-15:58:07 1|worker-webpack  | filePath of Watcher /Users/gita/code/experimental
```

And then I get a whole bunch of errors stating `ENOTDIR`. These are just the first few ...

```2020-12-10-15:58:08 1|worker-webpack  | Watchpack Error (watcher): Error: ENOTDIR: not a directory, watch '/Users/gita/code/experimental/Users/gita'
2020-12-10-15:58:08 1|worker-webpack  | Watchpack Error (watcher): Error: ENOTDIR: not a directory, watch '/Users/gita/code/experimental/Users/gita/code'
2020-12-10-15:58:08 1|worker-webpack  | Watchpack Error (watcher): Error: ENOTDIR: not a directory, watch '/Users/gita/code/experimental/Users/gita/code/experimental'
2020-12-10-15:58:08 1|worker-webpack  | Watchpack Error (watcher): Error: ENOTDIR: not a directory, watch '/Users/gita/code/experimental/Users/gita/code/experimental/modules'
```

It looks like it is incorrectly nesting the base context directory? It it doubling over the base directory path.
Any fix/hints? 

Versions:
webpack 5.10.0
watchpack 2.1.0

**Comment by alexander-akait** [comment]
Can you create reproducible test repo?

**Comment by gita-v** [comment]
> Can you create reproducible test repo?

I tried to reproduce w/ minimal repo but I am having issues -- will continue to try & let you know.

**Comment by gita-v** [comment]
For this I was still unable to reproduce w/ small repo -- I just did work around by ignoring that path when it doubles

**Comment by alexander-akait** [comment]
What is os?

**Comment by gita-v** [comment]
Mac Catalina: 10.15.6

**Comment by alexander-akait** [comment]
Very weird, don't have ideas, what is wrong :confused: Anyway ideas how we can debug it?

**Comment by gita-v** [comment]
When the initial directorypath and filepath are set up they are being initialized incorrectly I think, hence the double path that is created. If the filepath is already in directorypath it should begin from that one. Let me try and compare watchpack to the previous version to see what has changed

**Comment by alexander-akait** [comment]
Feel free to feedback

**Comment by Aghassi** [comment]
I'm also seeing this issue, and you can reproduce it with this PR https://github.com/bazelbuild/rules_nodejs/pull/2431. Simply remove the line `'/private/**/private/**'` from the `ignored` field under `watchOptions` and it will fail. You can run the example by running `./start.sh` from within the example folder. The use case we are working under is that we need Webpack Dev Server in watch mode to cooperate with Bazel, and Bazel is heavily based around creating symlinks back to the source files. 

I've gone ahead and added `console.log` locally and can see the following stack trace

```
parent: /private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5
parent: /private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot
parent: /private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898
parent: /private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5/private/var/tmp/_bazel_david.aghassi
parent: /private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5/private/var/tmp
parent: /private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5/private/var
parent: /private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5/private
parent: /private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5
parentResolved: /private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5
realFile: /private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5/private
/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5/private
/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/node_modules/watchpack/lib/LinkResolver.js:98
				throw e;
				^

Error: ENOENT: no such file or directory, readlink '/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5/private'
    at Object.readlinkSync (fs.js:934:3)
    at Object.fs.readlinkSync (/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/external/build_bazel_rules_nodejs/internal/node/node_patches.js:251:57)
    at LinkResolver.resolve (/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/node_modules/watchpack/lib/LinkResolver.js:51:27)
    at LinkResolver.resolve (/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/node_modules/watchpack/lib/LinkResolver.js:37:31)
    at LinkResolver.resolve (/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/node_modules/watchpack/lib/LinkResolver.js:37:31)
    at LinkResolver.resolve (/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/node_modules/watchpack/lib/LinkResolver.js:37:31)
    at LinkResolver.resolve (/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/node_modules/watchpack/lib/LinkResolver.js:37:31)
    at LinkResolver.resolve (/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/node_modules/watchpack/lib/LinkResolver.js:37:31)
    at LinkResolver.resolve (/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/node_modules/watchpack/lib/LinkResolver.js:37:31)
    at LinkResolver.resolve (/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/node_modules/watchpack/lib/LinkResolver.js:37:31) {
  errno: -2,
  syscall: 'readlink',
  code: 'ENOENT',
  path: '/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5/bazel-out/darwin-fastbuild/bin/serve.sh.runfiles/examples_webpack5/private'
}
```

What it looks like is happening is the root file path is not being computed right, and since there are files in the tree that point to other files in `/private` it is trying to find them under the root, but that will always fail. In this case, the correct path should be `/private/var/tmp/_bazel_david.aghassi/33292cf1c253e9dfad80eedae63f9898/execroot/examples_webpack5` for the file it is looking up.

**Comment by Aghassi** [comment]
To the above bug that I was seeing, @gregmagolan helped me track it down and we opened #188

**Comment by gita-v** [comment]
The merge did not resolve my issue 🤔 Mine is maybe something else

**Comment by alexander-akait** [comment]
Fixed
